from typing import Any

import structlog
from anthropic import (
    APIConnectionError,
    APIError,
    APIStatusError,
    AsyncAnthropic,
    RateLimitError,
)

from src.clients.llm.adapters.base import BaseLLMAdapter, RetryKind
from src.clients.llm.base import (
    CompletionRequest,
    CompletionResponse,
    WebSearchConfig,
    WebSource,
)
from src.core.config import settings

logger = structlog.get_logger(__name__)

# 서버 도구 루프가 pause_turn으로 끊길 때 재호출하는 최대 횟수(무한루프 가드)
_MAX_TOOL_TURNS = 8
# 회수 본문 총 예산(토큰) — 200k 컨텍스트에서 시스템·검색결과·생성분을 뺀 안전선.
# 페이지당 상한 = min(cfg.max_content_tokens, 예산 // max_uses)로 곱이 항상 예산 이하.
_FETCH_BUDGET_TOKENS = 100_000
# provider-중립 web_search → Anthropic 서버 도구 버전.
# _20260209(동적 필터링)는 Opus 4.6+/Sonnet 4.6+ 전용 — Haiku 등 구형 모델은
# basic 변형을 써야 한다(아니면 400). 모델별 선택은 _web_tool_types.
_WEB_SEARCH_TYPE = "web_search_20260209"
_WEB_FETCH_TYPE = "web_fetch_20260209"
_BASIC_WEB_SEARCH_TYPE = "web_search_20250305"
_BASIC_WEB_FETCH_TYPE = "web_fetch_20250910"


def _web_tool_types(model: str) -> tuple[str, str]:
    """웹도구 변형 선택 — 전 모델 basic 고정(2026-08-07).

    동적 필터링 변형(_WEB_SEARCH_TYPE)은 서버가 검색을 code_execution 컨테이너
    안에서 돌린다. 그 턴이 pause_turn으로 끊기면 재전송이 400
    "container_id is required when there are pending tool uses generated by code
    execution with tools"로 거부되는데, 응답의 container.id를 messages.create의
    `container`로 되돌려줘도 해소되지 않았다(Sonnet 실측 2회, 챕터 6/7 전멸).
    수집은 검색 결과만 쓰므로 동적 필터링의 이득이 없고, basic 변형은 컨테이너를
    쓰지 않아 재전송이 성립한다(Haiku 런 17건 수집 실증).
    """
    return _BASIC_WEB_SEARCH_TYPE, _BASIC_WEB_FETCH_TYPE


# temperature를 받지 않는 모델 접두사 — 지정하면 400(deprecated for this model).
_NO_TEMPERATURE_PREFIXES = (
    "claude-fable-5",
    "claude-sonnet-5",
    "claude-opus-5",
    "claude-opus-4-8",
    "claude-opus-4-7",
)


def _accepts_temperature(model: str) -> bool:
    return not model.startswith(_NO_TEMPERATURE_PREFIXES)


# output_config.effort를 받는 모델 접두사 — 그 외(Haiku 4.5 등)에 보내면 400.
# effort는 추론(thinking) 깊이와 토큰 지출을 낮추는 GA 파라미터(베타 헤더 불요).
_EFFORT_PREFIXES = (
    "claude-fable-5",
    "claude-opus-5",
    "claude-opus-4-8",
    "claude-opus-4-7",
    "claude-opus-4-6",
    "claude-sonnet-5",
    "claude-sonnet-4-6",
)


def _accepts_effort(model: str) -> bool:
    return model.startswith(_EFFORT_PREFIXES)


# pause_turn 재전송에서 대형 PDF를 걷어낼 때 자리에 남기는 안내문.
PDF_RESEND_PLACEHOLDER = "[PDF 본문 생략 — 재전송 제한 회피. URL로만 참조하라]"


def _is_base64_source(node: dict[str, Any]) -> bool:
    """base64 첨부 source 딕셔너리인가 — 중첩 경로가 아니라 값으로 판정한다.

    web_fetch 결과의 문서 블록은 SDK/도구 버전에 따라 중첩이 달라진다. 경로를
    고정하면 버전이 바뀔 때 조용히 못 잡으므로(2026-08-06 3차 재발), 형태로만 본다.
    """
    if "data" not in node:
        return False
    if node.get("type") == "base64":
        return True
    return "pdf" in str(node.get("media_type") or "").lower()


# 재전송에서 회수 본문을 남겨 둘 길이와 자리 안내문. 우리 추출은 매 턴
# _collect_sources가 끝내므로(본문은 그때 web_sources로 확보된다) 재전송분을 잘라도
# **우리가 잃는 것은 없다** — PDF를 걷어내는 것과 같은 논리다. 모델은 앞머리와 URL로
# 무엇이었는지 알아보고, 정말 필요하면 다시 회수한다.
FETCH_RESEND_KEEP_CHARS = 1500
FETCH_RESEND_NOTICE = "…[이하 본문 생략 — 재전송 누적 회피. 필요하면 URL로 다시 회수하라]"


def _trim_long_text(node: Any, limit: int) -> tuple[Any, int]:
    """중첩 구조를 재귀 순회하며 긴 문자열을 잘라낸다. → (치환본, 자른 건수)

    호출부가 **도구 결과 블록 안에서만** 부른다 — 모델 자신의 텍스트(진행 메모·최종
    매니페스트 JSON)를 자르면 매니페스트가 깨져 출처 매칭이 통째로 소실된다.
    """
    if isinstance(node, str):
        if len(node) > limit:
            return node[:limit] + FETCH_RESEND_NOTICE, 1
        return node, 0
    if isinstance(node, dict):
        out: dict[str, Any] = {}
        total = 0
        for key, value in node.items():
            out[key], n = _trim_long_text(value, limit)
            total += n
        return out, total
    if isinstance(node, list):
        items: list[Any] = []
        total = 0
        for value in node:
            item, n = _trim_long_text(value, limit)
            items.append(item)
            total += n
        return items, total
    return node, 0


def _trim_fetched_bodies(dumped: Any, limit: int = FETCH_RESEND_KEEP_CHARS) -> tuple[Any, int]:
    """도구 결과 블록이면 그 안의 긴 본문을 자른다. 아니면 그대로 둔다.

    블록 유형은 `..._tool_result`로 끝나는 형태를 통째로 본다 — web_fetch·web_search가
    각각 다르고 도구 버전에 따라 또 바뀌므로 이름을 고정하지 않는다(경로를 고정했다가
    세 번 재발한 _sanitize_for_resend의 교훈).
    """
    if not isinstance(dumped, dict):
        return dumped, 0
    if not str(dumped.get("type") or "").endswith("tool_result"):
        return dumped, 0
    return _trim_long_text(dumped, limit)


def _scrub_base64_sources(node: Any) -> tuple[Any, int]:
    """중첩 구조를 재귀 순회하며 base64 source를 텍스트 안내로 치환. → (치환본, 건수)"""
    if isinstance(node, dict):
        if _is_base64_source(node):
            return (
                {"type": "text", "media_type": "text/plain", "data": PDF_RESEND_PLACEHOLDER},
                1,
            )
        out: dict[str, Any] = {}
        total = 0
        for key, value in node.items():
            out[key], n = _scrub_base64_sources(value)
            total += n
        return out, total
    if isinstance(node, list):
        items: list[Any] = []
        total = 0
        for value in node:
            item, n = _scrub_base64_sources(value)
            items.append(item)
            total += n
        return items, total
    return node, 0


# 캐시 브레이크포인트를 붙여도 안전한 블록 유형 — 서버 도구 결과·텍스트.
# 목록에 없는 유형(thinking 등)에 붙이면 400으로 챕터가 통째로 죽으므로 보수적으로 간다.
_CACHEABLE_BLOCK_TYPES = frozenset(
    {
        "text",
        "tool_use",
        "tool_result",
        "server_tool_use",
        "web_search_tool_result",
        "web_fetch_tool_result",
        "document",
    }
)


def _block_to_dict(block: Any) -> Any:
    """SDK 블록 → dict. 변환 못 하면 원본 그대로(그 블록엔 경계를 못 찍을 뿐)."""
    if isinstance(block, dict):
        return block
    for attr in ("model_dump", "to_dict"):
        fn = getattr(block, attr, None)
        if callable(fn):
            try:
                return fn()
            except Exception:  # pragma: no cover - SDK 변경 방어
                return block
    if hasattr(block, "__dict__"):
        return dict(vars(block))
    return block


def _as_blocks(content: Any) -> list[Any] | None:
    """메시지 content를 블록 리스트로 정규화(가능한 것만 dict로)."""
    if isinstance(content, str):
        return [{"type": "text", "text": content}]
    if not isinstance(content, list):
        return None
    return [_block_to_dict(b) for b in content]


def _move_cache_boundary(messages: list[dict[str, Any]]) -> None:
    """캐시 브레이크포인트를 대화 끝으로 옮긴다(롤링).

    pause_turn 재전송은 직전 턴까지의 대화를 통째로 다시 보낸다 — 회수한 페이지
    본문이 거기 쌓인다. 경계가 첫 요청 메시지에만 있으면 그 앞부분(수백 토큰)만
    캐시되고, Haiku는 최소 캐시 길이가 4,096토큰이라 그마저 무시된다. 실측(7일):
    수집 입력 14.3M 중 캐시 읽기 2.4M = 14%뿐이고 비용의 절반이 여기였다.
    끝으로 옮기면 직전 턴까지 전부가 다음 턴의 캐시 프리픽스가 된다.
    """
    if not messages:
        return
    for m in messages:  # 이전 경계 제거 — 브레이크포인트는 4개 상한이 있다
        if isinstance(m.get("content"), list):
            for b in m["content"]:
                if isinstance(b, dict):
                    b.pop("cache_control", None)
    last = messages[-1]
    blocks = _as_blocks(last.get("content"))
    if not blocks:
        return
    target = next(
        (
            b
            for b in reversed(blocks)
            if isinstance(b, dict) and b.get("type") in _CACHEABLE_BLOCK_TYPES
        ),
        None,
    )
    if target is None:
        return
    target["cache_control"] = {"type": "ephemeral"}
    last["content"] = blocks


class AnthropicAdapter(BaseLLMAdapter):
    provider = "anthropic"

    def _create_client(self, api_key: str) -> Any:
        # max_retries=0: 재시도는 BaseLLMAdapter가 소유한다. SDK가 타임아웃된
        # 서버도구 턴을 내부에서 재실행하면 응답 없이 서버측 과금만 반복된다.
        return AsyncAnthropic(
            api_key=api_key,
            timeout=settings.llm_client_timeout_s,
            max_retries=0,
        )

    def _classify_error(self, exc: Exception) -> RetryKind | None:
        if isinstance(exc, RateLimitError):
            return "rate_limit"
        if isinstance(exc, APIConnectionError):
            return "retryable"
        if isinstance(exc, APIStatusError):
            return "fatal" if exc.status_code < 500 else "retryable"
        if isinstance(exc, APIError):
            return "retryable"
        return None

    async def _call_provider(self, request: CompletionRequest) -> CompletionResponse:
        assert self._client is not None
        if request.web_search is not None:
            return await self._call_with_web_search(request)

        # Anthropic Messages API: system은 messages가 아니라 별도 파라미터
        anth_messages: list[dict[str, Any]] = [
            {"role": m.role, "content": m.content} for m in request.messages if m.role != "system"
        ]
        # 공유 프리픽스 브레이크포인트 — 분할 생성처럼 [프리픽스, 가변 tail] 메시지로
        # 나눠 보내는 호출은 프리픽스 경계에 캐시를 찍어 2번째 호출부터 0.1배로 읽는다.
        # 최소 캐시 길이(Sonnet 1,024·Haiku 4,096토큰) 미만이면 API가 조용히 무시.
        if request.cache_prefix_messages > 0 and anth_messages:
            idx = min(request.cache_prefix_messages, len(anth_messages)) - 1
            boundary = anth_messages[idx]
            if isinstance(boundary["content"], str):
                boundary["content"] = [
                    {
                        "type": "text",
                        "text": boundary["content"],
                        "cache_control": {"type": "ephemeral"},
                    }
                ]
        kwargs: dict[str, Any] = {
            "model": request.model,
            "messages": anth_messages,
            "max_tokens": request.max_tokens,
        }
        # 신형 모델(Sonnet 5·Opus 4.7+)은 temperature를 400으로 거부한다
        # ("`temperature` is deprecated for this model", 2026-08-08 실측).
        # 거부 모델에선 후보 다양성·재생성 온도 상향이 무의미해진다(기본 샘플링만).
        if _accepts_temperature(request.model):
            kwargs["temperature"] = request.temperature
        # 추론 예산: thinking 기본-on 모델(Opus 5)의 작성 콜은 추론이 출력으로 과금돼
        # 비용 지배 구간이었다($33.84 런 실측: 출력 661k 중 본문 ~260k). 호출자가
        # effort를 낮춰 보내면 그대로 전달 — 미지원 모델이면 400 예방 차원에서 생략.
        if request.effort and _accepts_effort(request.model):
            kwargs["output_config"] = {"effort": request.effort}
        if request.system:
            kwargs["system"] = self._cacheable_system(request.system)

        result = await self._client.messages.create(**kwargs)
        text_blocks = [getattr(b, "text", "") for b in result.content]
        return CompletionResponse(
            content="".join(text_blocks),
            input_tokens=result.usage.input_tokens,
            output_tokens=result.usage.output_tokens,
            cached_input_tokens=getattr(result.usage, "cache_read_input_tokens", 0) or 0,
            cache_write_input_tokens=getattr(result.usage, "cache_creation_input_tokens", 0) or 0,
            model=result.model,
            stop_reason=result.stop_reason or "end_turn",
        )

    @staticmethod
    def _cacheable_system(system: str) -> list[dict[str, Any]]:
        """system을 블록 리스트로 감싸 끝에 캐시 브레이크포인트를 찍는다.

        문자열 system엔 브레이크포인트를 둘 수 없어 같은 페르소나를 쓰는 후속 호출
        (동일 절 후보 2개, 재작성, pm_verify 반복)이 매번 전액을 낸다. 모델별 최소
        캐시 길이(Sonnet 1,024·Haiku 4,096토큰) 미만이면 API가 조용히 무시하므로
        짧은 system에 붙여도 손해는 없다.
        """
        return [{"type": "text", "text": system, "cache_control": {"type": "ephemeral"}}]

    # web_search(server tool) 경로
    async def _call_with_web_search(self, request: CompletionRequest) -> CompletionResponse:
        assert self._client is not None
        cfg = request.web_search
        assert cfg is not None
        tools = self._build_web_tools(cfg, request.model)

        anth_messages: list[dict[str, Any]] = [
            {"role": m.role, "content": m.content} for m in request.messages if m.role != "system"
        ]
        # 프롬프트 캐싱 브레이크포인트 2단: ① 마지막 요청 메시지 끝(고정 프리픽스),
        # ② top-level 자동 배치(매 턴 마지막 블록). pause_turn 재전송은 이전 턴까지의
        # 대화(회수 본문 포함)를 통째로 다시 보내는데, 캐싱이 없으면 그 전부를 매 턴
        # 전액 재과금당한다 — 수집 비용 지배 구간(2026-08-06 실측 런당 ~$2.4-2.6).
        # ①은 한 턴의 블록 수가 캐시 조회 한도(20블록)를 넘어 ②의 체인이 끊겨도
        # 시스템+도구+요청 프리픽스만은 항상 재사용되게 하는 안전망이다.
        _move_cache_boundary(anth_messages)
        sources: dict[str, dict[str, Any]] = {}  # url -> WebSource 필드(부분 누적)
        text_parts: list[str] = []
        in_tok = out_tok = cached_tok = cache_write_tok = 0
        stop_reason = "end_turn"
        model = request.model
        container_id: str | None = None

        for _ in range(_MAX_TOOL_TURNS):
            kwargs: dict[str, Any] = {
                "model": request.model,
                "messages": anth_messages,
                "max_tokens": request.max_tokens,
                "tools": tools,
            }
            if request.effort and _accepts_effort(request.model):
                kwargs["output_config"] = {"effort": request.effort}
            if request.system:
                kwargs["system"] = self._cacheable_system(request.system)
            # 동적 필터링 웹도구(비-Haiku)는 서버가 code_execution 컨테이너 안에서
            # 검색을 돌린다. pause_turn 재전송에는 그 컨테이너 id를 함께 보내야
            # 한다 — 없으면 400 "container_id is required when there are pending
            # tool uses"로 챕터 수집이 통째로 죽는다(2026-08-07 Sonnet 첫 런 실측).
            if container_id is not None:
                kwargs["container"] = container_id
            # temperature는 의도적으로 생략: Opus 4.8/4.7 등은 temperature를 400으로 거부한다.

            # 스트리밍 필수 — 서버 도구를 많이 쓰는 턴은 비스트리밍 요청의 10분
            # 상한을 넘겨 APITimeoutError로 죽는다(재시도 3회 = 챕터당 30분 낭비).
            async with self._client.messages.stream(**kwargs) as stream:
                result = await stream.get_final_message()
            container = getattr(result, "container", None)
            if container is not None and getattr(container, "id", None):
                container_id = container.id
            in_tok += result.usage.input_tokens
            out_tok += result.usage.output_tokens
            cached_tok += getattr(result.usage, "cache_read_input_tokens", 0) or 0
            cache_write_tok += getattr(result.usage, "cache_creation_input_tokens", 0) or 0
            self._collect_sources(result.content, sources)
            text_parts += [
                getattr(b, "text", "") for b in result.content if getattr(b, "type", "") == "text"
            ]
            stop_reason = result.stop_reason or "end_turn"
            model = result.model
            # 턴별 캐시 효과 — 합계만 보면 '경계가 안 먹은 것'과 '새 내용이 많은 것'을
            # 구분할 수 없다(2026-08-10 진단).
            logger.info(
                "anthropic.web_turn",
                turn=len(anth_messages),
                fresh=result.usage.input_tokens,
                cache_read=getattr(result.usage, "cache_read_input_tokens", 0) or 0,
                cache_write=getattr(result.usage, "cache_creation_input_tokens", 0) or 0,
                stop=stop_reason,
            )

            if stop_reason == "pause_turn":
                # 서버 도구 루프 한도 → assistant content blocks를 돌려보내 이어간다.
                # 단, 대형 PDF 회수 결과는 생략(아래 _sanitize_for_resend 참고).
                anth_messages.append(
                    {"role": "assistant", "content": self._sanitize_for_resend(result.content)}
                )
                # 다음 턴의 캐시 프리픽스 = 방금 턴까지 전부.
                _move_cache_boundary(anth_messages)
                continue
            break

        if stop_reason == "max_tokens":
            # 최종 텍스트(매니페스트 JSON)가 잘리면 신뢰도·매칭섹션이 조용히
            # 소실된다(회수 본문은 web_sources로 살아남음) — 침묵하지 않는다.
            logger.warning(
                "anthropic.web_search.truncated",
                model=model,
                max_tokens=request.max_tokens,
                n_sources=len(sources),
            )
        web_sources = [WebSource(**fields) for fields in sources.values()]
        return CompletionResponse(
            content="".join(text_parts),
            input_tokens=in_tok,
            output_tokens=out_tok,
            cached_input_tokens=cached_tok,
            cache_write_input_tokens=cache_write_tok,
            model=model,
            stop_reason=stop_reason,
            web_sources=web_sources,
        )

    @staticmethod
    def _build_web_tools(cfg: WebSearchConfig, model: str) -> list[dict[str, Any]]:
        search_type, fetch_type = _web_tool_types(model)
        search: dict[str, Any] = {
            "type": search_type,
            "name": "web_search",
            "max_uses": cfg.max_uses,
        }
        if cfg.user_country:
            search["user_location"] = {"type": "approximate", "country": cfg.user_country}
        if cfg.allowed_domains:
            search["allowed_domains"] = cfg.allowed_domains
        if cfg.blocked_domains:
            search["blocked_domains"] = cfg.blocked_domains
        tools: list[dict[str, Any]] = [search]
        if cfg.fetch_pages:
            # 회수 횟수는 검색과 분리한다 — 검색은 PDF를 끌어오지 않고 회수만 끌어온다.
            # 서버 도구 루프가 한 요청 안에서 회수분을 누적하는데 PDF 100페이지를
            # 넘으면 서버가 400을 뱉고, 그 시점엔 우리가 개입할 응답 자체가 없다
            # (2026-08-06 실측: 12콜 중 6콜 전멸, 챕터 통째 0건).
            fetch_uses = max(
                1, cfg.max_fetch_uses if cfg.max_fetch_uses is not None else cfg.max_uses
            )
            # 불변식: 회수 본문 총량(fetch 횟수 × 페이지당 상한)이 컨텍스트 예산을
            # 넘지 못하게 페이지당 상한을 자동 축소한다. max_uses만 올리고 상한을
            # 잊어도 prompt too long(200k 초과)이 구조적으로 재발하지 않게 하는 장치.
            # ※ 이 상한은 PDF 등 바이너리엔 적용되지 않는다(SDK 타입 주석) — PDF
            #    누적 제동은 오직 fetch_uses다.
            per_page = min(
                cfg.max_content_tokens,
                max(4_000, _FETCH_BUDGET_TOKENS // fetch_uses),
            )
            fetch: dict[str, Any] = {
                "type": fetch_type,
                "name": "web_fetch",
                "max_uses": fetch_uses,
                "max_content_tokens": per_page,
            }
            # 도메인 필터는 검색·회수 양쪽에 일관 적용 — 검색만 거르면 모델이
            # 검색 밖 URL(본문 내 링크 등)을 회수해 필터를 우회할 수 있다.
            if cfg.allowed_domains:
                fetch["allowed_domains"] = cfg.allowed_domains
            if cfg.blocked_domains:
                fetch["blocked_domains"] = cfg.blocked_domains
            tools.append(fetch)
        return tools

    def _collect_sources(self, blocks: Any, sources: dict[str, dict[str, Any]]) -> None:
        """Anthropic server-tool 결과 블록을 WebSource 필드로 정규화해 url별로 누적."""
        for b in blocks:
            btype = getattr(b, "type", "")
            if btype == "web_search_tool_result":
                content = getattr(b, "content", None)
                if isinstance(content, list):  # 성공 시 list[WebSearchResultBlock] (에러면 객체)
                    for r in content:
                        if getattr(r, "type", "") != "web_search_result":
                            continue
                        url = getattr(r, "url", "")
                        if not url:
                            continue
                        s = sources.setdefault(url, {"url": url})
                        if getattr(r, "title", None) and not s.get("title"):
                            s["title"] = r.title
                        if getattr(r, "page_age", None):
                            s["page_age"] = r.page_age
            elif btype == "web_fetch_tool_result":
                content = getattr(b, "content", None)  # WebFetchBlock | 에러 블록
                if getattr(content, "type", "") == "web_fetch_result":
                    url = getattr(content, "url", "")
                    doc = getattr(content, "content", None)  # DocumentBlock
                    text = self._extract_doc_text(doc)
                    if url and text:
                        s = sources.setdefault(url, {"url": url})
                        s["content_md"] = text
                        doc_title = getattr(doc, "title", None)
                        if doc_title and not s.get("title"):
                            s["title"] = doc_title

    @staticmethod
    def _sanitize_for_resend(blocks: Any) -> list[Any]:
        """pause_turn 재전송에서 회수 결과를 줄인다 — PDF는 치환, 긴 본문은 절단.

        web_fetch가 회수한 100페이지 초과 PDF는 재전송 시 API가 400으로 거부해
        챕터 수집 전체를 죽인다. 크기 임계값(500k)으로 거르던 1차 시도는 얇은
        장문 PDF를 놓쳐 재발했고, 이어진 2차 시도는 `web_fetch_tool_result →
        content → content → source` 고정 경로를 getattr로 훑었는데 실제 블록의
        중첩이 달라 **한 건도 못 잡고 조용히 통과**해 3차 재발했다(2026-08-06
        실측: 6장 중 4장 수집 전멸, 치환 로그 0건·예외 0건).

        그래서 경로가 아니라 **값**으로 판정한다 — 블록을 dict로 덤프해 재귀
        순회하며 base64 source를 전부 치환한다. 중첩 위치나 필드명이 바뀌어도
        걸린다. 우리 추출 경로는 PDF 본문을 쓰지 않아(_extract_doc_text가 PDF는
        None) 잃는 것이 없다.

        HTML 본문은 치환이 아니라 **절단**한다. 걷어내지 않았더니 재전송마다 누적돼
        입력 상한을 넘겼다(2026-08-19 스모크: 1,136,960 > 200,000 토큰으로 1장 수집이
        통째로 실패, 자료 2건). 여기서도 잃는 것은 없다 — _collect_sources가 매 턴
        돌아 본문을 web_sources로 이미 확보한 뒤에 이 함수가 불린다. 모델 자신의
        텍스트(진행 메모·최종 매니페스트)는 도구 결과 블록이 아니라 건드리지 않는다.
        """
        out: list[Any] = []
        n_stripped = 0
        n_trimmed = 0
        n_blocks = 0
        for b in blocks:
            n_blocks += 1
            try:
                dumped = b.model_dump() if hasattr(b, "model_dump") else b
                scrubbed, n_pdf = _scrub_base64_sources(dumped)
                trimmed, n_txt = _trim_fetched_bodies(scrubbed)
                if n_pdf or n_txt:
                    out.append(trimmed)
                    n_stripped += n_pdf
                    n_trimmed += n_txt
                    continue
            except Exception:
                # 치환 실패는 원본 재전송으로 폴백하되 반드시 흔적을 남긴다 —
                # 조용히 삼키면 PDF 400 재발 시 원인 추적이 불가능하다(1차 교훈).
                logger.warning("anthropic.pdf_sanitize_failed", exc_info=True)
            out.append(b)
        # 0건도 남긴다 — '치환기가 돌았지만 못 잡았다'와 'PDF가 없었다'를 로그로
        # 구분할 수 있어야 한다(2차 시도가 조용히 실패한 원인).
        logger.info(
            "anthropic.pdf_stripped_on_resend",
            n=n_stripped,
            n_trimmed=n_trimmed,
            n_blocks=n_blocks,
        )
        return out

    @staticmethod
    def _extract_doc_text(doc: Any) -> str | None:
        # DocumentBlock.source = PlainTextSource(type="text", data=...) | Base64PDFSource
        source = getattr(doc, "source", None)
        if source is None:
            return None
        if getattr(source, "type", "") == "text":
            return getattr(source, "data", None)
        return None  # PDF/base64 등은 PoC 범위 밖
